tinymce.addI18n('nl',{
"Cut": "Knippen",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "U browser ondersteund geen toegang tot het clipboard. Gelieve ctrl+X\/C\/V te gebruiken.",
"Paste": "Plakken",
"Close": "sluiten",
"Align right": "rechts uitlijnen",
"New document": "Nieuw document",
"Numbered list": "nummer lijst",
"Increase indent": "inspringen vergroten",
"Formats": "formaten",
"Select all": "Alles selecteren",
"Undo": "Ongedaan maken",
"Strikethrough": "doorstreept",
"Bullet list": "bol lijst",
"Superscript": "superscript",
"Clear formatting": "geen opmaak",
"Subscript": "subscript",
"Redo": "Opnieuw",
"Ok": "Ok\u00e9",
"Bold": "Vet",
"Italic": "Schuin",
"Align center": "gecentreerd uitlijnen",
"Decrease indent": "inspringen verkleinen",
"Underline": "onderstreept",
"Cancel": "annuleren",
"Justify": "justify",
"Copy": "Kopi\u00ebren",
"Align left": "links uitlijnen",
"Visual aids": "Hulpmiddelen",
"Lower Greek": "greek verlagen",
"Square": "Vierkant",
"Default": "Standaard",
"Lower Alpha": "Alpha verlagen",
"Circle": "Circel",
"Disc": "Disc",
"Upper Alpha": "Alpha vergroten",
"Upper Roman": "Roman vergroten",
"Lower Roman": "Roman verlagen",
"Name": "Naam",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "U hebt niet alles opgeslagen, bent u zeker dat u de pagina wenst te verlaten?",
"Restore last draft": "Herstel het laatste ontwerp",
"Special character": "Speciale karakters",
"Source code": "Broncode",
"Right to left": "Rechts naar links",
"Left to right": "Links naar rechts",
"Emoticons": "emoticons",
"Robots": "Robots",
"Document properties": "Document eigenschappen",
"Title": "Titel",
"Keywords": "sleutelwoorden",
"Encoding": "Codering",
"Description": "Omschrijving",
"Author": "Auteur",
"Fullscreen": "Volledig scherm",
"Horizontal line": "Horizontale lijn",
"Source": "Bron",
"Constrain proportions": "verhoudingen behouden",
"Dimensions": "Dimensie's",
"Insert\/edit image": "afbeelding invoegen\/bewerken",
"Image description": "Afbeelding omschrijving",
"Insert date\/time": "voeg datum\/tijd in",
"Url": "Url",
"Text to display": "tekst laten zien",
"Insert link": "Hyperlink invoegen",
"New window": "Nieuw venster",
"None": "Geen",
"Target": "doel",
"Insert\/edit link": "Hyperlink invoegen\/bewerken",
"Insert\/edit video": "Video invoegen\/bewerken",
"General": "Algemeen",
"Poster": "Poster",
"Alternative source": "Alternatieve bron",
"Paste your embed code below:": "Plak u in te sluiten code hieronder:",
"Insert video": "Video invoegen",
"Embed": "insluiten",
"Nonbreaking space": "vaste spatie invoegen",
"Page break": "pagina-einde",
"Preview": "Voorbeeld",
"Print": "Print",
"Save": "Opslaan",
"Could not find the specified string.": "Geen resultaten gevonden",
"Replace": "Vervang",
"Next": "Volgende",
"Whole words": "alleen hele worden",
"Find and replace": "Zoek en vervang",
"Replace with": "Vervangen door",
"Find": "Zoeken",
"Replace all": "Vervang allemaal",
"Match case": "Overeenkomen",
"Prev": "Vorige",
"Spellcheck": "Spellingscontrole",
"Finish": "Einde",
"Ignore all": "Negeer allemaal",
"Ignore": "Negeer",
"Insert row before": "Voeg rij in voor",
"Rows": "Rijen",
"Height": "Hoogte",
"Paste row after": "Plak rij achter",
"Alignment": "uitlijning",
"Column group": "kolom groep",
"Row": "Rij",
"Insert column before": "Voeg kolom in voor",
"Split cell": "Cel splitsen",
"Cell padding": "cel pading",
"Cell spacing": "celruimte",
"Row type": "Rij type",
"Insert table": "Tabel invoegen",
"Body": "Body",
"Caption": "onderschrift",
"Footer": "voettekst",
"Delete row": "Verwijder rij",
"Paste row before": "Plak rij voor",
"Scope": "wijdte",
"Delete table": "Verwijder tabel",
"Header cell": "koptekstcel",
"Column": "Kolo",
"Cell": "Cel",
"Header": "hoofdtekst",
"Border": "Rand",
"Cell type": "cel type",
"Copy row": "Kopieer rij",
"Row properties": "Rij eigenschappen",
"Table properties": "Tabel eigenschappen",
"Row group": "rij groep",
"Right": "Rechts",
"Insert column after": "Voeg kolom in na",
"Cols": "kollomen",
"Insert row after": "voeg rij in achter",
"Width": "Breedte",
"Cell properties": "Cel eigenschappen",
"Left": "Links",
"Cut row": "Knip rij",
"Delete column": "Verwijder kolom",
"Center": "Midden",
"Merge cells": "Cellen samenvoegen",
"Insert template": "Sjabloon invoegen",
"Templates": "Sjablonen",
"Background color": "Achtergrondkleur",
"Text color": "Tekstkleur",
"Show blocks": "Blokken tonen",
"Show invisible characters": "Laat onzichtbare karakters zien",
"Words: {0}": "Woorden: {0}",
"Insert": "Invoegen",
"File": "Bestand",
"Edit": "Bewerk",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Druk ALT-F9 voor de menu. Druk ALT-F10 voor de toolbar. Druk ALT-0 voor de help.",
"Tools": "gereedschap",
"View": "Beeld",
"Table": "Tabel",
"Format": "Opmaak"
});